# #1. 创建nova,nova_api,nova_cell0 数据库
- name: Create nova databases
  mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ item }}"
    state: present
  loop:
    - nova
    - nova_api
    - nova_cell0

# 2. 对nova 用户给nova,nova_api,nova_cell0 数据库授予ALL权限
# 采取追加授权方式
- name: Grant privileges to nova user on databases
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: nova
    password: "{{ NOVA_DBPASS }}"
    host: "{{ item.host }}"
    priv: "{{ item.privileges }}"
    append_privs: yes   # 追加授权方式
    state: present
  loop:
    - { host: 'localhost', privileges: "nova.*:ALL" }
    - { host: '%', privileges: "nova.*:ALL" }
    - { host: 'localhost', privileges: "nova_api.*:ALL" }
    - { host: '%', privileges: "nova_api.*:ALL" }
    - { host: 'localhost', privileges: "nova_cell0.*:ALL" }
    - { host: '%', privileges: "nova_cell0.*:ALL" }