- name: enable neutron-linuxbridge-agent service
  systemd:
    name: neutron-linuxbridge-agent
    enabled: yes

- name: restart neutron-linuxbridge-agent.service 
  systemd:
    name: neutron-linuxbridge-agent
    state: restarted
  

# 放到nova中重启
# - name: restart openstack-nova-compute.service
#   systemd:
#     name: openstack-nova-compute.service
#     state: restarted